### ISSUE TITLE
Git History

### ISSUE THREAD

**Issue by HelloKitty** [Falstring/Dalaran-Core#1]
The repository is missing the git history of the project from the point of its fork from Trinitycore at the very least. This history is absolutely essential to extract potential value from the source's publishing.

If you can wipe the repository and push it with the git history that would be helpful for many developers.

**Comment by Falstring** [comment]
I do not have the git history unfortunately... files were compressed in a zip folder.

**Comment by BarbzYHOOL** [comment]
That could as well be a dalaran wow from 2016 (as indicated in some comments)

**Comment by Falstring** [comment]
It's from mid 2018.

**Comment by Ali-Khazaee** [comment]
is there anticheat on this source ? so we can inspire from it

**Comment by BarbzYHOOL** [comment]
How do you know Falstring? Posted in mid 2018 doesn't mean it's from 2018 :P

I compared one boss script from TC to the dalaran one, and the TC one seemed much more complete.

**Comment by Falstring** [comment]
It's from 2018... the old 2016 source is way different. You can try to compare the two.

**Comment by Chenocide** [comment]
Can't really say about mid 2018 but there's proof that it's from late 2017.
